name: chiqimlarim
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  intl: ^0.19.0
  modal_bottom_sheet: ^3.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  vibration: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/note.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/note.png"

flutter:
  uses-material-design: true